<h2 align="center">Codebasics DL Course: Tensors in PyTorch 2</h2>

In [6]:
import torch

### Tensor Attributes

In [7]:
units = torch.tensor([
    [200, 220],  # Product A (iPhone)
    [150, 180],  # Product B (iPad)
    [300, 330]   # Product C (MacBook)
])

In [8]:
units.shape

torch.Size([3, 2])

In [9]:
units.dtype

torch.int64

In [10]:
units.device

device(type='cpu')

### Tensor Reshaping

In [11]:
units.view(-1)

tensor([200, 220, 150, 180, 300, 330])

In [12]:
units.view(2,3)

tensor([[200, 220, 150],
        [180, 300, 330]])

In [13]:
units.view(6,1)

tensor([[200],
        [220],
        [150],
        [180],
        [300],
        [330]])

### Index Operator

In [14]:
units

tensor([[200, 220],
        [150, 180],
        [300, 330]])

In [15]:
units[2,0]

tensor(300)

In [16]:
units[2,0] = 305
units

tensor([[200, 220],
        [150, 180],
        [305, 330]])

### Tensor Creation with Specific Values

In [17]:
torch.zeros((2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [18]:
torch.ones((3,5))

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [19]:
torch.rand((3,5))

tensor([[0.7006, 0.4909, 0.8684, 0.3559, 0.5162],
        [0.6579, 0.8850, 0.8110, 0.1318, 0.9117],
        [0.7083, 0.0506, 0.9012, 0.3270, 0.8999]])